<h1 style="font-size:45px; font-weight:bold; color:blue"> FONDAMENTAUX DU LANGAGE PYTHON</h1>

Par Mamadou NDIAYE

# Listes

Les listes peuvent contenir plusieurs types de données (chaînes de caractères, entiers naturels, nombres décimaux, dictionnaires, dataframes, listes, etc.). Les listes sont définies par : [ ].

In [8]:
# Exemple de liste avec []
liste = [19, 'SDakar', 7.5, 'neige', ['riz', 'tomate', 'banane']]
liste

[19, 'SDakar', 7.5, 'neige', ['riz', 'tomate', 'banane']]

In [9]:
# Premier élément d'une liste
print(liste[0])

# Dernier élément d'une liste
print(liste[-1])
print(liste[-1] == liste[4])

19
['riz', 'tomate', 'banane']
True


In [10]:
# Méthode append permet d'ajouter un élément à la fin d'une liste
liste.append(5)
liste

[19, 'SDakar', 7.5, 'neige', ['riz', 'tomate', 'banane'], 5]

In [11]:
my_list = []
for i in range(10):
    squared = i**2
    my_list.append(squared)
my_list    
    

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

Le code ci-dessus peut être écrit en une seule ligne avec une liste de compréhension

In [12]:
# Création d'une liste de compréhension
my_list2 = [i**2 for i in range(10)]
my_list2

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [13]:
my_list == my_list2

True

La méthode insert() est utilisée pour insérer des éléments dans une liste à une position donnée.

In [14]:
# Insertion de 'New York' à la deuxième position dans liste
liste.insert(1, 'New York')
liste

[19, 'New York', 'SDakar', 7.5, 'neige', ['riz', 'tomate', 'banane'], 5]

# <h1 style="font-size:35px; font-weight:bold; color:red">Tableaux numpy (numpy arrays)</h1>


La différence entre une liste et un tableau numpy est que le dernier contient des données de même type. Un tableau numpy est défini avec la méthode <strong>array()</strong> de la librairie <i>numpy</i>

In [15]:
# Importantion de la librairie numpy

import numpy as np

In [16]:
# Création d'un tableau numpy

tab_nump = np.array([0,1,2,3,4,5,6,7,8,9])
print(tab_nump)
print(type(tab_nump))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


Les listes et les tableaux numpy diffèrent par leur vitesse et leur efficacité de mémoire. Une raison intuitive à cela est que les listes python doivent stocker la valeur de chaque élément ainsi que le type de chaque élément (car les types peuvent différer). Alors que les tableaux numpy n'ont besoin de stocker le type qu'une seule fois, car il est le même pour tous les éléments du tableau.

Vous pouvez effectuer des calculs avec des tableaux numpy.

In [17]:
# Division par 2 de chaque élément de tab_nump

print(type(tab_nump/2))

<class 'numpy.ndarray'>


In [18]:
# Création d'un liste des 10 premiers entiers naturels

first_number = [0,1,2,3,4,5,6,7,8,9]

#first_number/2

In [19]:
# Division par 2 de chaque élément de first_number

first_number = np.array(first_number)

first_number/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [20]:
np.array([i for i in range(10)])/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

Pour des études scientifiques, le stockage dans des tableaux numpy est préféré car il permet d'effectuer des calculs de manière rapide et efficace.

In [21]:
# Méthode append()

tab_nump = np.append(tab_nump, 10)

tab_nump

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

 L'attribut <strong>shape</strong> donne la dimension (nombre de lignes et nombre de colonnes d'un tableau numpy).

In [22]:
# Attribut shape d'un tableau numpy

tab_nump.shape

(11,)

In [23]:
# Création d'un tableau numpy 2x2

x = np.array([[1,2], [3,4]])
x

array([[1, 2],
       [3, 4]])

In [24]:
# Dimension de x

x.ndim

2

Vous pouvez effectuer des opérations basiques (addition, soustraction, multiplication et division) avec les tableaux numpy.

In [25]:
# Création d'un tableau numpy

y = np.array([[5,6], [7,8]])
y

array([[5, 6],
       [7, 8]])

In [26]:
# x + y
sum_x_y = x + y
sum_x_y

array([[ 6,  8],
       [10, 12]])

In [27]:
# x + y avec la méthide add() de numpy

sum2_x_y = np.add(x, y)
sum2_x_y

array([[ 6,  8],
       [10, 12]])

In [28]:
sum2_x_y == sum_x_y 

array([[ True,  True],
       [ True,  True]])

In [29]:
# x - y avec la methode subtract() de numpy

diff_x_y = np.subtract(x, y)
diff_x_y

array([[-4, -4],
       [-4, -4]])

In [30]:
# x * y avec la méthode de multiply() de numpy 
prod_x_y = np.multiply(x, y)
prod_x_y

array([[ 5, 12],
       [21, 32]])

In [31]:
# x / y avec la méthode de divide() de numpy 

div_x_y = np.divide(x, y)
div_x_y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [32]:
# Création d'un tableau numpy 3x4 (3 lignes et 4 colonnes)

z = np.array([[1,2,3,4], [5,6,7,8], [9, 10, 11, 12]])
z

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
z.shape

(3, 4)

In [34]:
# première ligne de z
z[0]

array([1, 2, 3, 4])

In [35]:
# première ligne de z
z[0, :]

array([1, 2, 3, 4])

In [36]:
# dernière ligne de z
z[-1]

array([ 9, 10, 11, 12])

In [37]:
# dernière ligne de z
z[-1, :]

array([ 9, 10, 11, 12])

In [38]:
# Deuxième colonnes de z
z[:,1]

array([ 2,  6, 10])

In [39]:
# Dernière colonnes de z
z[:, -1]

array([ 4,  8, 12])

In [40]:
z

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
# Récupération d'une matrice particulière à partir de z
#[[ 6,  7],
# [10, 11]]

z[1:, 1:3]

array([[ 6,  7],
       [10, 11]])

In [42]:
# Récupérer l'élément de z à la dernière ligne et dernière colonne
z[-1, -1]

12

In [43]:
# Modifier l'élément de z à la dernière ligne et deuxième colonne

z[0, 1] = 1000
z

array([[   1, 1000,    3,    4],
       [   5,    6,    7,    8],
       [   9,   10,   11,   12]])

<h1 style="font-size:35px; font-weight:bold; color:red">Dictionnaires</h1>

Les dictionnaires sont des objets utilisés pour le stockage de paires clés-valeurs. Ils sont indexés par les clés. Chaque clé d'un dictionnaire doit être unique mais les valeurs n'ont pas besoin d'être uniques. Dans python, vous pouvez créer un dictionnaire avec : <strong>{ }</strong>. 

In [44]:
# Création d'un dictionnaire qui stocke le prix d'ouverture et le volume moyen

stock_price = {'AAPL':[122.02, 14093522,],
              'GOOG': [1798.10, 1821738],
              'AMZN':[3221.65, 51435858],
              'FB': [285.36, 20847907]}
stock_price

{'AAPL': [122.02, 14093522],
 'GOOG': [1798.1, 1821738],
 'AMZN': [3221.65, 51435858],
 'FB': [285.36, 20847907]}

In [45]:
# Récupération des valeurs de la clé 'FB'

stock_price['FB']

[285.36, 20847907]

In [46]:
# Ajout d'une nouvelle paire clé-valeur dans un dictionnaire

stock_price['TSLA']= [556.44, 52485698]
stock_price

{'AAPL': [122.02, 14093522],
 'GOOG': [1798.1, 1821738],
 'AMZN': [3221.65, 51435858],
 'FB': [285.36, 20847907],
 'TSLA': [556.44, 52485698]}

In [47]:
# Changement de la valeur d'une clé

stock_price['GOOG'] = [1897.5, 1821738]
stock_price

{'AAPL': [122.02, 14093522],
 'GOOG': [1897.5, 1821738],
 'AMZN': [3221.65, 51435858],
 'FB': [285.36, 20847907],
 'TSLA': [556.44, 52485698]}

Vous pouvez récupérer toutes les clés d'un dictionnaire en utilisant la méthode <strong>keys()</strong>

In [48]:
# Clés d'un dictionnaire

stock_price.keys()

dict_keys(['AAPL', 'GOOG', 'AMZN', 'FB', 'TSLA'])

Vous pouvez récupérer toutes les valeurs d'un dictionnaire en utilisant la méthode <strong>values()</strong>

In [49]:
# Valeurs d'un dictionnaire
stock_price.values()

dict_values([[122.02, 14093522], [1897.5, 1821738], [3221.65, 51435858], [285.36, 20847907], [556.44, 52485698]])

<h1 style="font-size:35px; font-weight:bold; color:red">Dataframe</h1>

La dataframe est la structure de données la plus utilisée en Statistiques et en Data Science. Une dataframe permet de stocker les données en deux dimensions (lignes et colonnes) et rend ainsi l'analyse de données plus aisée.

Pour travailler avec les dataframes dans Python, il est nécessaire d'importer la librairie Pandas

In [50]:
# Importation de Pandas

import pandas as pd

In [51]:
# Création d'une dataframe à partir d'un dictionnaire

df = pd.DataFrame(stock_price)
df

AAPL       GOOG         AMZN           FB         TSLA
0       122.02     1897.5      3221.65       285.36       556.44
1  14093522.00  1821738.0  51435858.00  20847907.00  52485698.00

En réalité, les vraies variables, qui devraient être les colonnes de la dataframe, sont le prix d'ouverture et le volume moyen d'actions négociées. Pour un meilleur affichage, vous pouvez faire la transposition de la dataframe.

In [52]:
# Transposée de df

df = df.T
df

0           1
AAPL   122.02  14093522.0
GOOG  1897.50   1821738.0
AMZN  3221.65  51435858.0
FB     285.36  20847907.0
TSLA   556.44  52485698.0

La méthode <strong>raname()</strong> est utilisée pour renommer les colonnes d'une dataframe.

In [53]:
# Renommez les colonnes de df : 'price' pour 0 et 'avg_volume' pour 1

df.columns = ['price', 'avg_volume']
df
      # ou tou simplement:
      # df.rename(columns = {0:'price', 1:'avg_volume'}, inplace = True)

price  avg_volume
AAPL   122.02  14093522.0
GOOG  1897.50   1821738.0
AMZN  3221.65  51435858.0
FB     285.36  20847907.0
TSLA   556.44  52485698.0

In [54]:
# Colonnes d'une dataframe

df.columns

Index(['price', 'avg_volume'], dtype='object')

In [55]:
# Indices de lignes d'une dataframe

df.index

Index(['AAPL', 'GOOG', 'AMZN', 'FB', 'TSLA'], dtype='object')

Il est possible, et c'est souvent le cas, de créer une dataframe en important un fichier .csv, .json, .xlsx, etc soit à partir d'un ordinateur local ou d'internet. <br><br>
Par exemple, pour importer un fichier .csv, il faut connaître le chemin qui mène à ce fichier dans votre ordinateur ou l'url de ce fichier sur internet. La focntion <strong>read_csv()</strong> de la librairie Pandas permet de faire cette opération


In [57]:
# Importation des données (fichier 'segmentation data.csv')

clients = pd.read_csv('segmentation data.csv')

# Affichage des cinq premières lignes
clients.head()


ID  Sex  Marital status  Age  Education  Income  Occupation  \
0  100000001    0               0   67          2  124670           1   
1  100000002    1               1   22          1  150773           1   
2  100000003    0               0   49          1   89210           0   
3  100000004    0               0   45          1  171565           1   
4  100000005    0               0   53          1  149031           1   

   Settlement size  
0                2  
1                2  
2                0  
3                1  
4                1

La méthode <strong>head()</strong> affiche par défaut les cinq premières lignes. Mais vous pouvez choisir d'afficher par exemple les 10 ptremières lignes avec <strong>.head(10)</strong> 

In [ ]:
clients.tail()

Pour avoir des informations sur la structure de la dataframe, vous pouvez utiliser la méthode <strong>info()</strong>. Cette méthode donne des informations comme le nombre de lignes et de colonnes de la dataframe, le type des données dans chaque variable (colonne), le nombre de valeurs non-manquantes dans chaque variable, etc.

In [ ]:
# Structure de la dataframe

clients.info()

Supposons que vous vouliez travailler uniquement avec les colonnes 'ID', 'Age', 'Education' et 'Income'. Il s'agira donc de créer une nouvelle dataframe comprenant uniquement ces colonnes.

In [ ]:
# Séléction de plusieurs colonnes

clients_new = clients[['ID', 'Age', 'Education', 'Income']]
clients_new.head()

Vous vous rendez compte que vous n'aviez pas besoin de la colonne 'ID'. Pour la supprimer, il faut utiliser la méthide <strong>drop()</strong>

In [ ]:
# Suppression de la colonne d'une dataframe. Pour supprimer une colonnes il faut toujours préciser axis=1

clients_new = clients_new.drop('ID')


In [ ]:
clients_new

<h1 style="font-size:35px; font-weight:bold; color:red">Les fonctions</h1>

Si vous commencez à copier/coller à plusieurs reprises un extrait de code, alors c'est un signal qu'il faut créer une fonction à partir de ce code; En effet, le fait de copier/coller du code est une grande source d'erreurs. Placer l'extrait du code dans une fonction permet de bien structurer votre programme et d'éviter des erreurs. <br><br>Créer une fonction dans python est une tâche hyper simple. Même si on peut créer des fonctions sans arguments, le plus fréquent est la création de fonction avec un ou plusieurs arguments aisni qu'une sortie?

In [61]:
# Création d'une fonction qui prend deux arguments et retourne leur somme

def somme(x, y):
    return x + y

somme(10,12)

22

In [62]:
# Autres exemple d'uitilisation de la fonctio  somme()

somme('Pa', 'ris')

'Paris'

Les fonctions <strong>lambda</strong> permettent d'écrire des fonctions rapidement et à la volée (en une seule ligne de code) en utilisant le mot-clé <strong>lambda</strong>. Le fomat d'une fonction lambda est :<br> <i>lambda arguments: expression</i>

In [63]:
# Création d'une fonction lambda

somme_lambda = lambda a, b: a + b

somme_lambda(6,8)

14

In [64]:
# Création d'une fonction lambda
squared_lambda = lambda i:i**2

squared_lambda(2)

4

In [4]:
# Consulation de l'aide d'une fonction help()
help(pd.read_csv)

Help on function read_csv in module pandas.io.parsers.readers:

read_csv(filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]', *, sep: 'str | None | lib.NoDefault' = <no_default>, delimiter: 'str | None | lib.NoDefault' = None, header: "int | Sequence[int] | None | Literal['infer']" = 'infer', names: 'Sequence[Hashable] | None | lib.NoDefault' = <no_default>, index_col: 'IndexLabel | Literal[False] | None' = None, usecols=None, squeeze: 'bool | None' = None, prefix: 'str | lib.NoDefault' = <no_default>, mangle_dupe_cols: 'bool' = True, dtype: 'DtypeArg | None' = None, engine: 'CSVEngine | None' = None, converters=None, true_values=None, false_values=None, skipinitialspace: 'bool' = False, skiprows=None, skipfooter: 'int' = 0, nrows: 'int | None' = None, na_values=None, keep_default_na: 'bool' = True, na_filter: 'bool' = True, verbose: 'bool' = False, skip_blank_lines: 'bool' = True, parse_dates=None, infer_datetime_format: 'bool' = False, keep_date_col: 'bool' = F

AttributeError: 'NoneType' object has no attribute 'to_list'